### ISSUE TITLE
Cheerio SUAP future

### ISSUE THREAD

**Issue by zaqmarlon** [isaacmsl/cheerio-suap#7]
1. This tool aim to get only user's data, can it be used to make analysis?
2. What If SUAP's website HTML structure changes?

**Comment by isaacmsl** [comment]
Why is it all in english? I think that is important do it in Portuguese, because is more easy to students understand. (To version 2.0.0)

**Comment by zaqmarlon** [comment]
There is a way to use SUAP API, See on [myf](https://github.com/L-Marcel/myf)
